ChengFengOAuth/Controllers/NotificationController.cs
using ChengFengOAuth.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ChengFengOAuth.Controllers
{
    [Authorize]
    public class NotificationController : Controller
    {
        private const string _lineNotifyEndpoint = "https://notify-api.line.me/api/notify";
        private readonly SubscriberContext _subscriberContext;
        private readonly HttpClient _httpClient;

        public NotificationController(SubscriberContext subscriberContext, IHttpClientFactory httpClientFactory)
        {
            _subscriberContext = subscriberContext;
            _httpClient = httpClientFactory.CreateClient();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendMessageToSubscriber( string? message)
        {
            if (string.IsNullOrEmpty(message))
                return BadRequest();
            List<Subscriber> subscribers = (from sub in _subscriberContext.Subscriber select sub).ToList();

            foreach(Subscriber subscriber in subscribers)
            {
                await SendMessage(subscriber.AccessToken, message);
            }

            await Task.CompletedTask;
            return new JsonResult(new { success = true});
        }

        private async Task<bool> SendMessage(string access_token, string message)
        {
            Dictionary<string, string> body = new Dictionary<string, string>()
            {
                {"message", message},
                {"stickerPackageId", "11537"},
                {"stickerId", "52002752"},
            };

            HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Post, _lineNotifyEndpoint);
            requestMessage.Content = new FormUrlEncodedContent(body);
            requestMessage.Headers.Add("Authorization", $"Bearer {access_token}");
            HttpResponseMessage responseMessage = await _httpClient.SendAsync(requestMessage);

            return responseMessage.IsSuccessStatusCode;
        }
    }
}

ChengFengOAuth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChengFengOAuth</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChengFengOAuth.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">ChengFengOAuth</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">首頁</a>
                        </li>
                        @{
                            bool? subscribe = (bool?)TempData["Subscribe"];
                            TempData["Subscribe"] = subscribe;
                            if (subscribe == null || subscribe == false)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Subscription" asp-action="Index">訂閱通知</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Subscription" asp-action="Unsubscribe">取消訂閱</a>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Notification" asp-action="Index">推播訊息</a>
                        </li>
                    </ul>
                    @if (TempData["UserName"] != null)
                    {
                        <div class="user-name-div">@TempData["UserName"]</div>
                        TempData["UserName"] = TempData["UserName"];
                        <a class="nav-link text-dark" asp-controller="Account" asp-action="Signout">Signout</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main id="main" role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>